name: icon-theme-yaru-mate
architectures:
  - build-on: amd64
    run-on: all
version: '22.04.4'
summary: Yaru MATE is the default theme for Ubuntu MATE 21.04 and newer.
description: |
  Snap of the Yaru MATE icon theme.

# We build against Ubuntu 20.04 packages, but use the "bare" base as
# we don't want to force installation of a large base snap.
build-base: core20
base: bare

grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Yaru-MATE-dark
        - $SNAP/share/icons/Yaru-MATE-light

parts:
  icons:
    after:
      - utils
    plugin: dump
    source: "https://github.com/ubuntu-mate/ubuntu-mate-artwork/archive/refs/tags/$SNAPCRAFT_PROJECT_VERSION.tar.gz"
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
        mv $SNAPCRAFT_PART_INSTALL/usr/share/icons/Yaru-MATE* $SNAPCRAFT_PART_INSTALL/share/icons/
        $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/Yaru-MATE*

  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
